# _config.yml
title: "About Zikun"
logo: "assets/img/portrait.jpg"
description: "Pursuing Master of Information Science"
remote_theme: "pages-themes/minimal@v0.2.0"
show_downloads: false
plugins:
  - jekyll-remote-theme
links:
  - title: GitHub
    url: https://github.com/ZikunFu/
  - title: LinkedIn
    url: https://www.linkedin.com/in/zikun-fu/
  - title: CV
    url: https://zikunfu.github.io/assets/pdf/resume.pdf
  - title: Email
    url: mailto:zikun.fu@ontariotechu.net